### ISSUE TITLE
Forwarded scheme vs proto

### ISSUE THREAD

**Issue by jiripudil** [nette/http#101]
There might be a bug in Forwarded implementation (#94) – I haven't delved deep into it, but just at first glance: `RequestFactory` [checks for the `scheme` parameter](https://github.com/nette/http/blob/487864cb20cb0d740772e1910bb8f871d450b224/src/Http/RequestFactory.php#L236) in the header, while the RFC [defines a `proto` parameter](https://tools.ietf.org/html/rfc7239#section-5.4). Has anyone run into this issue and can confirm?

**Comment by dg** [comment]
ping @patrickkusebauch
