### ISSUE TITLE
Session in memcached:  Nette\InvalidStateException  Unable to clear session lock record

### ISSUE THREAD

**Issue by dakorpar** [nette/http#110]
This is in my config.neon
```
session:
    saveHandler: memcached
    savePath: 'localhost:22121'

```
and I repetedly get this problem...

memcached config is ok, and this test code:

```
$m = new Memcached();
$m->addServer('localhost', 22121);

$m->set('int', 99);
```
sets key correctly
```

Dumping memcache contents
  Number of buckets: 1
  Number of items  : 1
Dumping bucket 1 - 1 total items
add int 1 1479504298 2
99
```

I'm using php 7.0.12
and memcached 1.4.15

also basic php code:
```
ini_set('session.save_handler', 'memcached');
ini_set('session.save_path', 'localhost:11211');
session_start();
$_SESSION['BLA'] = 'heeey';

```
saved key to memcached without any issue and it's possible to read it

also if I set config directly to php.ini it works and session is correctly saved to memcached, but on other request session is lost (I think session id got changed, session data is in memcached)

**Comment by dg** [comment]
Can you try if these examples work to? Different order:

```
ini_set('session.save_handler', 'memcached');
ini_set('session.save_path', 'localhost:11211');
```

or 

```
ini_set('session.save_handler', 'memcached');
session_save_path('localhost:11211');
```

or 

```
session_save_path('localhost:11211');
ini_set('session.save_handler', 'memcached');
```
