### ISSUE TITLE
Is UserStorage::setExpiration with BROWSER_CLOSED working?

### ISSUE THREAD

**Issue by forrest79** [nette/http#112]
Hi,
we're using Nette\Security\User::setExpiration with $whenBrowserIsClosed = TRUE, that calls Nette\Security\UserStorage::setExpiration with flag BROWSER_CLOSED, but I think, that this functionality was removed in pullrequest #103 and then Nette\Security\User::setExpiration function with parametr $whenBrowserIsClosed and flag BROWSER_CLOSED for Nette\Security\UserStorage::setExpiration is unusable and should be removed too.

**Comment by dg** [comment]
Good point.
