### ISSUE TITLE
Problem with Line 148

### ISSUE THREAD

**Issue by carstomas** [nette/http#119]
**Nette\Http\RequestFactory**

If the 148 line includes:
foreach ($list as &$v)

dump files:
array (1)
   files => array (1)
   |  0 => NULL

---
BUT
If the 148 line includes:
while (list(, $v) = each($list))

dump files:
array (1)
   files => array (1)
   |  0 => Nette\Http\FileUpload #ee05

---

Where is problem? Thank you.

**Comment by dg** [comment]
Please write snippet of code to reproduce bug.

**Comment by carstomas** [comment]
Nette\Http\RequestFactory

BUG
start line 148
```
foreach ($list as &$v) {
			if (!isset($v['name'])) {
				continue;

			} elseif (!is_array($v['name'])) {
				if (!$this->binary && (!preg_match($reChars, $v['name']) || preg_last_error())) {
					$v['name'] = '';
				}
				if ($v['error'] !== UPLOAD_ERR_NO_FILE) {
					$v['@'] = new FileUpload($v);
				}
				continue;
			}

			foreach ($v['name'] as $k => $foo) {
				if (!$this->binary && is_string($k) && (!preg_match($reChars, $k) || preg_last_error())) {
					continue;
				}
				$list[] = [
					'name' => $v['name'][$k],
					'type' => $v['type'][$k],
					'size' => $v['size'][$k],
					'tmp_name' => $v['tmp_name'][$k],
					'error' => $v['error'][$k],
					'@' => &$v['@'][$k],
				];
			}
		}

```
---
NO BUG
```
while (list(, $v) = each($list)) {
			if (!isset($v['name'])) {
				continue;

			} elseif (!is_array($v['name'])) {
				if (!$this->binary && (!preg_match($reChars, $v['name']) || preg_last_error())) {
					$v['name'] = '';
				}
				if ($v['error'] !== UPLOAD_ERR_NO_FILE) {
					$v['@'] = new FileUpload($v);
				}
				continue;
			}

			foreach ($v['name'] as $k => $foo) {
				if (!$this->binary && is_string($k) && (!preg_match($reChars, $k) || preg_last_error())) {
					continue;
				}
				$list[] = [
					'name' => $v['name'][$k],
					'type' => $v['type'][$k],
					'size' => $v['size'][$k],
					'tmp_name' => $v['tmp_name'][$k],
					'error' => $v['error'][$k],
					'@' => &$v['@'][$k],
				];
			}
		}
```

Is it correctly written?

**Comment by dg** [comment]
I don't understand. What is wrong? It produces invalid output? For which input?

**Comment by carstomas** [comment]
I'm sorry, but I don't know exactly how to describe it properly.
When I upload file by input file multiple and after submitted using dump, output is:
files => array (1)
   | 0 => NULL
but I changing the line 148 to
```
while (list(, $v) = each($list))
```
output is:
files => array (1)
| 0 => Nette\Http\FileUpload

Is it clear?

**Comment by dg** [comment]
dump global variable `$_FILES`

**Comment by carstomas** [comment]
array (1)
   files => array (5)
   |  name => array (1)
   |  |  0 => "1a.jpg" (6)
   |  type => array (1)
   |  |  0 => "image/jpeg" (10)
   |  tmp_name => array (1)
   |  |  0 => "D:\Program Files\xampp\tmp\phpCB54.tmp" (38)
   |  error => array (1)
   |  |  0 => 0
   |  size => array (1)
   |  |  0 => 10979

**Comment by dg** [comment]
can you dump it as `var_export($_FILES)`?

**Comment by carstomas** [comment]
array ( 'files' => array ( 'name' => array ( 0 => '1a.jpg', ), 'type' => array ( 0 => 'image/jpeg', ), 'tmp_name' => array ( 0 => 'D:\\Program Files\\xampp\\tmp\\php116.tmp', ), 'error' => array ( 0 => 0, ), 'size' => array ( 0 => 10979, ), ), )

**Comment by dg** [comment]
It seems like bug in PHP 5, fixed
