### ISSUE TITLE
public hosting && url rewrite in .htaccess files && $_SERVER['SCRIPT_NAME'] problems

### ISSUE THREAD

**Issue by h0h0h** [nette/http#123]
### Description
Routing works fine on localhost.
Routing is broken after copying app to public web hosting (wedos.cz).
Some other people are reporting similar problems on wedos user forum.
I traced the problem to file `/http/src/http/RequestFactory.php`, line 95.
`$_SERVER['SCRIPT_NAME']` contains invalid value on public web hosting (it contained filesystem path instead of url) and so was not shortened, which then propagated to `urlScript.php`, `Routing.php`, etc..., so all routing was broken and no match was found for any processed requests.
After discovering that, it was easy to google problem description (https://www.google.com/search?q=htaccess+SCRIPT_NAME+problem). And workaround solution.
Problem disappeared after inserting line  `$path = $_SERVER["REQUEST_URI"];`  between lines 100 and 101. Application now seems to be working correcly on both localhost and public hosting. I have not installed command line interpreter or composer, so I cannot run unit tests and check that something else is not broken. Only have downloaded sandbox release and running it on xampp.

Nice framework guys, particularly the error prettifier (I didn't get much further yet). I can't understand how you managed to make such nice thing in php. I hate php. Here are some of the reasons: https://eev.ee/blog/2012/04/09/php-a-fractal-of-bad-design/  :-)

### Steps To Reproduce
Not sure.
I'm new to php, nette and apache, so it took me several days to find out the cause of this problem. Mainly because i was suspecting rules in multiple url-rewriting .htaccess files and was meddling with them. Also it is happening only on public hosting and I cannot check or replicate its configuration.

zdravím

**Comment by milo** [comment]
Estimate the correct URL is a little bit magic. I would bet, your patch will break other installations. You can:
1) Check, that `RewriteBase` in `.htaccess` is correct
2) make dump of `$_SERVER` and past it here.
