### ISSUE TITLE
getReferer method missing in IRequest

### ISSUE THREAD

**Issue by misaon** [nette/http#137]
- bug report? yes
- feature request? no
- version: 2.4.7

Hi, when i write `$this->getHttpRequest()->getReferer()` i encountered a problem when the IDE PhpStorm did not know about the `getReferer()` method. The reason is that the method is missing in **IRequest**. I want to ask if it is deliberate or a bug. It would be good either to add or add an appropriate annotation to the IDE to understand that the getReferer method is accessible.
...

![snimek obrazovky 2018-03-22 v 12 44 39](https://user-images.githubusercontent.com/15806356/37768703-dc01d34a-2dce-11e8-9dca-efe4e3fdbeaa.png)

**Comment by dg** [comment]
It is possible that there are more missing methods. But bad is that adding them to the interface is a big BC break…

**Comment by misaon** [comment]
@dg How about adding `@method Url|null getReferer() Returns referrer.` annotation to head of the interface like this? I tried and works great. Additionally, it does not create an BC break.

![snimek obrazovky 2018-03-23 v 9 38 28](https://user-images.githubusercontent.com/15806356/37819573-35dc6092-2e7e-11e8-8d09-9ebb8a0b39dc.png)

**Comment by dg** [comment]
It seems like solution
