### ISSUE TITLE
\Nette\Http\Url dots in query parameters

### ISSUE THREAD

**Issue by slischka** [nette/http#141]
Version: latest

### Bug Description
In query parameters dots are replaces to underscode.
The bug is from internal PHP function `parse_str`, where `.` are replaced to `_`.

### Steps To Reproduce
```
$url = new \Nette\Http\Url('test.xy?test.text=text');
return (string) $url; //returns: 'test.xy?test_text=text'
```

### Expected Behavior
should return: `test.xy?test.text=text`

**Comment by dg** [comment]
Can you fix it?

**Comment by slischka** [comment]
I can try. But not sure :D

**Comment by dg** [comment]
Ok, I merged it.
