### ISSUE TITLE
Session -> ISession, Session, ISessionStorage, NativeSessionStorage, ...

### ISSUE THREAD

**Issue by MartkCz** [nette/http#150]
Session split to 
- Session (interface ISession) 
- SessionStorage (interface ISessionStorage), implement php session to class NativeSessionStorage
- SessionSectionFactory (interface ISessionSectionFactory)
- SessionSection
- MetaBag, DataBag ????

I can try to send PR

**Comment by dg** [comment]
Why?

**Comment by MartkCz** [comment]
imho it's clearer and better for custom implementation
