### ISSUE TITLE
Reverse proxy

### ISSUE THREAD

**Issue by Ewwe** [nette/http#154]
Zdravim, mam tu nette 2.4 za reverse proxy, posilam si X-Forwarded-For, X-Forwarded-Host a dalsi. Aplikace ale pri presmerovani napr. na /sign/in pri stavbe url pouziva http_host misto http_x_forwared_host. V configu mam trusted ip te proxy. Mam workaround v podobe upravy RouterFactory.php, kam jsem na radek 253 pridal:

`if (!empty($_SERVER['HTTP_X_FORWARDED_HOST'])) {
    $url->setHost(str_replace([':80', ':443'], "", $_SERVER['HTTP_X_FORWARDED_HOST']));
}`

Nette v současné době vždy přesměruje na reverse proxy místo serveru který je za ním

**Comment by matej21** [comment]
You can set ip address of proxy server in config. Then nette will use x-forwarded headers: https://doc.nette.org/en/2.4/configuring#toc-http-proxies

**Comment by Ewwe** [comment]
V configuje proxy zapsaná

`http:
    proxy: 10.0.0.0/8`

**Comment by mabar** [comment]
Seems like Url object always uses original url, while Request object get one from X-Forwarded-Host.
Should it be updated [here](https://github.com/nette/http/blob/master/src/Http/RequestFactory.php#L331), @dg?

**Comment by Ewwe** [comment]
bump @dg

**Comment by dg** [comment]
@Ewwe @mabar Maybe there's a bug. I don't have much experience with this, so PR would be welcome.
