### ISSUE TITLE
Nette\Http\IResponse::setHeader() cannot get null as second parameter

### ISSUE THREAD

**Issue by integer** [nette/http#157]
Version: 3.0.1

### Bug Description
There is inconsistent definition in 
`\Nette\Http\IResponse::setHeader(string $name, string $value);`
vs
`\Nette\Http\Response::setHeader(string $name, ?string $value);`

So when you want to unset some header in `IResponse::send(\Nette\Http\IRequest $httpRequest, \Nette\Http\IResponse $httpResponse): void` method you are warn by IDE and static analysis tools that second parameter should not be NULL.

Problem is in code like this: `$httpResponse->setHeader('Set-Cookie', NULL);`

### Steps To Reproduce
in bug description

### Expected Behavior
No warning

### Possible Solution
Change `\Nette\Http\IResponse::setHeader` like this `setHeader(string $name, ?string $value);`

**Comment by mabar** [comment]
Add `deleteHeader()` to interface would be better https://github.com/nette/http/blob/4be7cde7f650c813b650f30db0b9d480225fa379/src/Http/Response.php#L131

**Comment by dg** [comment]
The preferred method is to use deleteHeader(), the IDE should be satisfied.

**Comment by integer** [comment]
But `deleteHeader()` method is not included in interface.
This method is not documented at https://doc.nette.org/en/3.0/http-request-response
This method does not exists for PHP language: https://3v4l.org/hoFN5i

So adding `@method` documentation comment is not solution but hack. Good enough to satisfy IDE but nothing more.

If it is temporary solution and you don't want to add BC break in interface before version 4, it would be OK. But I cannot find any clue about it in https://github.com/nette/http/commit/6856e82529bd740bfc5290580acb6dc85b8ea2e4

**Comment by dg** [comment]
> If it is temporary solution and you don't want to add BC break in interface before version 4, it would be OK. 

Yes, that's how it is.
