### ISSUE TITLE
Request - server parameters

### ISSUE THREAD

**Issue by mabar** [nette/http#166]
I am missing abstraction for `$_SERVER` in request. I would like to have `IRequest->getServerParameters()`. Should I send a PR?

**Comment by JanTvrdik** [comment]
Why? `$_SERVER` means nothing in HTTP context. It's just a collection a bunch of random stuff. It's better to have a specific methods like `getRequestUrl()` or `getHeaders()`.

**Comment by mabar** [comment]
E.g. sending files on-the-fly needs handling specific for `$_SERVER['SERVER_SOFTWARE']`
Some software solutions also add their variables in `$_SERVER` and I need to access them.

**Comment by dg** [comment]
And can you add some specific method for this purpose?

**Comment by mabar** [comment]
It should abstract all server variables, even custom ones, so not really
