### ISSUE TITLE
Absolute URL has no separator

### ISSUE THREAD

**Issue by KacerCZ** [nette/http#174]
Version: 3.0.3

### Bug Description
Behavior of `\Nette\Http\Url` changed in version 3.0 in case when only schema and path is set.

### Steps To Reproduce
```
$url = new \Nette\Http\Url('nette.org');
$url->setScheme('http');
echo $url;
```

### Expected Behavior
Result in version 2.4 was 'http://nette.org'.
In version 3.0 output is 'http:nette.org'.

### Possible Solution
Change bahvior back to version 2.4.

**Comment by dg** [comment]
It was broken in 2.4, see #171
