### ISSUE TITLE
Implement RFC 7239 (Forwarded HTTP Extension)

### ISSUE THREAD

**Issue by JanTvrdik** [nette/http#20]
`Nette\HttpRequestFactory` should support [RFC 7239 (Forwarded HTTP Extension)](https://tools.ietf.org/html/rfc7239). It may be wise to wait for servers to implement it first.

**Comment by patrickkusebauch** [comment]
About to implement it in legacy Nette 0.9 Application, where we configure our own reverse proxy. Once done there, I plan to port it for Nette\Http.
