### ISSUE TITLE
UrlImmutable should implement static get() method

### ISSUE THREAD

**Issue by janbarasek** [nette/http#201]
Class `UrlImmutable` should implement basic static method for get current URL.

Sample implementation:

```php
public static function get(): static
{
	if (!isset($_SERVER['HTTP_HOST'], $_SERVER['REQUEST_URI'])) {
		throw new \RuntimeException('URL detection is not available in CLI mode.');
	}
	$url = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http')
		. '://' . strtolower($_SERVER['HTTP_HOST']) . $_SERVER['REQUEST_URI'];
	return new static($url);
}
```

I know Singleton can be evil sometimes (https://phpfashion.com/singleton-sofie-s). On the other hand, having the ability to quickly access the actual URL is completely missing from the framework and has to be worked around in various ways.

Thanks.

**Comment by dg** [comment]
If you know it's wrong, why are you sending PR?

**Comment by janbarasek** [comment]
Because there is no simple native way to get the actual request URL.

**Comment by mabar** [comment]
`Nette\Http\IRequest->getUrl()`?

**Comment by janbarasek** [comment]
@mabar This notation is too complicated for beginners. You have to somehow get the request through the DIC, from which you only get the URL. If I want to figure out how to get the URL, I would expect to "somehow" create an instance of the URL and simply read the data.

**Comment by dg** [comment]
The fact that there is no simple way to get the current URL is no reason to implement it badly. 

Btw I think that this way is pretty simple: `(new RequestFactory)->fromGlobals()->getUrl()`
