### ISSUE TITLE
Error: Call to undefined function Nette\Http\imagetypes()

### ISSUE THREAD

**Issue by FCapobianchi** [nette/http#232]
Version:  3.2.3

### Bug Description
Error: Call to undefined function Nette\Http\imagetypes() in /vendor/nette/http/src/Http/FileUpload.php:220 

### Steps To Reproduce
if($file->isOk()){
    $systempath = dirname(dirname(__DIR__)). '/'.$this->neon["parameters"]["uploadsDir"].'/';
    $filename = $file->getSanitizedName();
    $filepath = rand(0,9).md5(uniqid(rand(), true))."/";
    $file->move( $systempath.$filepath.$filename);
    return [$filepath,$filename];
}

### Other info
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

PHP 7.4.3-4ubuntu2.19 (cli) (built: Jun 27 2023 15:49:59) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3-4ubuntu2.19, Copyright (c), by Zend Technologies

**Comment by mabar** [comment]
It's not very obvious from the error, but you probably don't have PHP extension GD installed.

**Comment by FCapobianchi** [comment]
sudo apt install php-gd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
php-gd is already the newest version (2:7.4+75).

**Comment by mabar** [comment]
Other reasons why may be [imagetypes](https://www.php.net/manual/en/function.imagetypes.php) missing is that GD extension is not loaded (check with `var_dump(get_loaded_extensions());`) or function is disabled (check with `echo ini_get('disable_functions');`)
Check via both http request and cli, they have separate .ini configs.

**Comment by FCapobianchi** [comment]
With this composer configuration "nette/http": "^3.1 < 3.2.3", the framework work correctly

**Comment by FCapobianchi** [comment]
Server restarted, problem solved!!! Thank's for your support!!!
