### ISSUE TITLE
Url::setQuery() BC break in Nette 2.3

### ISSUE THREAD

**Issue by enumag** [nette/http#48]
Calling `Url::setQuery()` with non-empty array that only contains `NULL` values causes a question mark to appear at the end of the generated url.

**Comment by JanTvrdik** [comment]
So its  a `getAbsoluteUrl()` bug? Feel free to send PR or wait for @dg to fix it for you.

**Comment by enumag** [comment]
@JanTvrdik Exactly. In this case my fix would probably be different then @dg's which means he would refactor it anyway so I'll just leave it to him.
