### ISSUE TITLE
SessionSection can't set expiration when browser close.

### ISSUE THREAD

**Issue by h4kuna** [nette/http#65]
I it look like as chrome bug, because chrome remeber $_COOKIE[nette-browser].

My chrome Linux 43.0.2357.125 (64-bit).

I try this on sanbox.
Add to presenter:
```php
public function handleSection() {
	$this->session->getSection('h4kuna')->value = 'ok';
	$this->redirect('this');
}


public function renderDefault() {
	$section = $this->session->getSection('h4kuna');
	$section->setExpiration(0);
	$this->template->section = $section->value ? : 'noValue';
}
```
add to latte:
```html
<a n:href="section!">fill section</a>
<br>
value: {$section} <br>
cookie nette-browser: {ifset $_COOKIE['nette-browser']}{$_COOKIE['nette-browser']}{else}ok does not exists{/ifset}
```

And use case is:
- run page, you will see value: noValue
- click to anchor (change session value)
- close browser
- open browser and it is remebered value, i expect noValue

Can anyone confirm?

Firefox and Opera works fine.

**Comment by dg** [comment]
And what can we do with Chrome bug (feature)?

**Comment by h4kuna** [comment]
For this moment I don't know how set expiration when browser close and I haven't solution how fix it.

I think you make nothing, bud is good know it. Because first time look like as nette bug after test in more browser look like only chrome bug. (feature)

**Comment by dg** [comment]
So can you add note to documentation?

**Comment by h4kuna** [comment]
Ok

**Comment by dg** [comment]
Fixed in documentation.
