### ISSUE TITLE
rawBody empty for PUT method

### ISSUE THREAD

**Issue by Zarganwar** [nette/http#73]
If nette called via PUT method, rawBody stay empty. If I try to read from php://input file_get_contents('php://input') after Nette\Http\RequestFactory::createHttpRequest() (in own router) there is right content.

Is it ok behavior?

**Comment by JanTvrdik** [comment]
What Nette version do you use? `$request->getRawBody()` should work with PUT method just fine.

**Comment by Zarganwar** [comment]
I am using 2.3.5 version. $request->rawBody for POST is OK, for PUT is empty.

**Comment by dg** [comment]
> The HTTP PUT request MUST contain a Content-Length header to specify the length (in bytes) of the body, or the server will not be able to know when the input stream is over. This is the common problem for many to find the php://input empty if no such header available. 

http://php.net/manual/en/features.file-upload.put-method.php

**Comment by f3l1x** [comment]
Could we close it? @Zarganwar @JanTvrdik ?
