### ISSUE TITLE
Session and PHP startup errors

### ISSUE THREAD

**Issue by enumag** [nette/http#80]
I'm trying to implement ajax upload today. However there is a problem with error handling. If I try to upload a too large file I get this error:

```
Possible problem: you are starting session while already having some data in output buffer. This may not work if the outputted data grows. Try starting the session earlier.
```

Session is started in `Container::initialialize()` of course. So I looked into the buffer and it contained this:

```
<b>Warning</b>: POST Content-Length of 360495939 bytes exceeds the limit of 31457280 bytes in <b>Unknown</b> on line <b>0</b><br />
```

This apparently is a PHP starup error. Everything works fine if I set the directive `diplay_startup_errors` to 0. But of course I don't want that - at least not in development.

Is there some other way to deal with this? If I'm not mistaken this pretty much means that `Nette\Http\Session` is incompatible with the directive `diplay_startup_errors`.

**Comment by dg** [comment]
It cannot be fixed in Nette
