### ISSUE TITLE
Starting session in CLI mode

### ISSUE THREAD

**Issue by enumag** [nette/http#89]
My functional tests are currently failing because of 

```
  [PHPUnit_Framework_Exception] Possible problem: you are starting session while already having some data in output buffer. This may not work if the outputted data grows. Try starting the session earlier.
```

Setting autoStart to true didn't help either because it's ignored in CLI mode. Why is it ignored and how should I fix my tests then?

https://travis-ci.org/Arachne/Forms/builds/125263850

Tried it on localhost as well with the same result.

**Comment by enumag** [comment]
Maybe [this](https://github.com/nette/http/commit/33f4dc821d6c63dfa36f8ed6506dfdd4c4291a15) is the correct fix. Should I send a PR?

**Comment by dg** [comment]
What about not starting session in CLI at all?

**Comment by enumag** [comment]
@dg Do you mean "What about not using session in tests at all?" or am I missing something?

**Comment by enumag** [comment]
@dg Thank you!
