### ISSUE TITLE
RequestFactory, REQUEST_URI and absolute URLs

### ISSUE THREAD

**Issue by ondrej-tuhacek** [nette/http#91]
Recently I installed this addon to Google Chrome:

[https://chrome.google.com/webstore/detail/host-switch-plus/bopepoejgapmihklfepohbilpkcdoaeo](https://chrome.google.com/webstore/detail/host-switch-plus/bopepoejgapmihklfepohbilpkcdoaeo)

its purpose is something like **etc/hosts** file with one single exception. If used, it sends HTTP requests like:

`GET http://www.example.com/ HTTP/1.1`

instead of 

`GET / HTTP/1.1`

which seems to be valid according to [https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html](https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html)

But Nette shows "no routes" and gives me 404.

Because RequestFactory.php where $_SEVER['REQUEST_URI'] is parsed cannot handle absolute URLs. I quick-fixed this simply by modifying urlFilters from:

```
	/** @var array */
	public $urlFilters = array(
		'path' => array('#/{2,}#' => '/'), // '%20' => ''
		'url' => array(), // '#[.,)]\z#' => ''
	);
```

to:

```
	/** @var array */
	public $urlFilters = array(
		'path' => array('#/{2,}#' => '/'), // '%20' => ''
		'url' => array('#^(http|ftp)s?://[^/]+/#' => '/'), // '#[.,)]\z#' => ''
	);
```

and it works, but I'm not sure if this is the best way to "fix" this.

**Comment by Majkl578** [comment]
According to [RFC 7230 ch. 5.3Request Target](https://tools.ietf.org/html/rfc7230#section-5.3), this is not valid.
> When making a request directly to an origin server, other than a
> CONNECT or server-wide OPTIONS request (as detailed below), a client
> MUST send only the absolute path and query components of the target
> URI as the request-target.

**Comment by ondrej-tuhacek** [comment]
Yes, you are right. In the most common used scenario it should be the **absolute path**, but in section 5.3.2 there is also **absolute form = absolute-URI** for proxies (and maybe the chrome add-on acts as a proxy - but I'm still not sure). And furthermore there is this sentence:

> To allow for transition to the absolute-form for all requests in some
   future version of HTTP, a server **MUST accept the absolute-form in
   requests, even though HTTP/1.1 clients will only send them in
   requests to proxies**.

So I would say that Nette should handle these requests as well. What do you think? Or do you think that I may rather sent bugreport to that chrome add-on vendor?

**Comment by dg** [comment]
Can you send PR? Absolute part should be stripped before `$urlFilters` are used.
