### ISSUE TITLE
$requestFactory->addUrlFilter doesn't work

### ISSUE THREAD

**Issue by SlavaAurim** [nette/http#99]
Nette 2.4

This code from docs generates the exception: _Call to undefined method Nette\Http\RequestFactory::addUrlFilter()_: 

```php
$requestFactory = new Nette\Http\RequestFactory;
$requestFactory->addUrlFilter('%20', '', PHP_URL_PATH);
```

**Comment by dg** [comment]
Fixed https://doc.nette.org/en/2.4/http-request-response#toc-requestfactory-and-url-filtering
